### ISSUE TITLE
Will gmail and/or other mailhosts block my ip?

### ISSUE THREAD

**Issue by MikeCraig418** [daveearley/Email-Validation-Tool#21]
Hello -

Should I consider the need for a proxy or rate-limiting? Do you know if anyone has been blacklisted for using this package in high-volume situations?

My initial test is ~30,000 emails. But I have a list of 450,000 that I would like to clean up

Thanks again! Beautiful package, and super easy to use.

**Comment by MikeCraig418** [comment]
Just to share with everyone, I used a VPN and performed 32,841 validations in 24 minutes.

![image](https://user-images.githubusercontent.com/23151962/85182203-cd473800-b23c-11ea-9932-0d1485240323.png)

It doesn't appear I had any blocking issues. I'm estimating 450,000 validations will take about 6 hours.

**Comment by daveearley** [comment]
Hey @949mac, thanks for the info.  From my experience you shouldn't see any rate limiting and don't need a proxy

**Comment by MikeCraig418** [comment]
Terrific. Thank you.

**Comment by MikeCraig418** [comment]
Also, to follow up, I successfully did 400,000 lookups in a little less than 4 hours! I kept the VPN just-in-case, but the difference in speed between VPN-on and off was negligible.

**Comment by daveearley** [comment]
Thanks for the update 👍
