### ISSUE TITLE
New release to get new email providers added

### ISSUE THREAD

**Issue by markitosgv** [daveearley/Email-Validation-Tool#29]
Hi,

Is it possible to release a new version to get new email providers? Thanks!

**Comment by daveearley** [comment]
Sure, I've created a new release with updated providers. Cheers

**Comment by markitosgv** [comment]
@daveearley please could you sync with packagist releases? Thanks!

**Comment by daveearley** [comment]
Syncing should be automatic

**Comment by markitosgv** [comment]
It seems it's not synced: https://packagist.org/packages/daveearley/daves-email-validation-tool
