### ISSUE TITLE
I’d like to get in touch with you

### ISSUE THREAD

**Issue by CatherineMaddenUXDX** [daveearley/Email-Validation-Tool#6]
Hi Dave,

I would like to say thank you for being involved in Open Source and discuss something regarding the UXDX conference which takes place in the RDS on October 5th.

Could you please send me your email address or drop me a message at catherine@uxdxconf.com?

Thanks in advance,
Catherine

**Comment by daveearley** [comment]
Hi @CatherineMaddenUXDX, I sent you an email just now 👍
